my_study_materials/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('markdownx/', include('markdownx.urls')),
    path('msmadmin/', admin.site.urls),
    path('', include('study_materials.urls')),
]

study_materials/urls.py
# Django 내장 모듈
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path
from django.views.static import serve

# 파이썬 표준 라이브러리
import os

# 현재 앱의 모듈
from . import views
from .sitemaps import StudyMaterialsSitemap
from .views import my_sitemap


sitemaps = {
    'study_materials': StudyMaterialsSitemap,
}

handler404 = 'study_materials.views.custom_404_view'

urlpatterns = [
    path('', views.index_view, name='index'),
    # allauth 라이브러리에서 제공하는 모든 url 패턴을 포함
    path('accounts/', include('allauth.urls')),

    # Notice
    path('notice/create_form/', views.notice_create_form,
         name='notice_create_form'),
    path('notice/create/', views.notice_create,
         name='notice_create'),
    path('notice/<int:notice_id>/', views.notice_detail,
         name='notice_detail'),
    path('notice/<int:notice_id>/update_form/', views.notice_update_form,
         name='notice_update_form'),
    path('notice/<int:notice_id>/update/', views.notice_update,
         name='notice_update'),
    path('notice/<int:notice_id>/delete/', views.notice_delete,
         name='notice_delete'),

    # Category
    path('category/create/', views.category_create, name='category_create'),
    path('categories/',
         views.category_list, name='category_list'),
    path('category/<int:category_id>/',
         views.category_detail, name='category_detail'),
    path('category/<int:category_id>/update/',
         views.category_update, name='category_update'),
    path('category/<int:category_id>/delete/',
         views.category_delete, name='category_delete'),
    path('category/<int:category_id>/subscribe/',
         views.category_subscribe, name='category_subscribe'),

    # Classification
    path('category/<int:category_id>/classification/create/>', views.classification_create,
         name='classification_create'),
    path('category/<int:category_id>/classifications/', views.classification_list,
         name='classification_list'),
    path('category/<int:category_id>/classification/<int:classification_id>/',
         views.classification_detail, name='classification_detail'),
    path('category/<int:category_id>/classification/update',
         views.classification_update, name='classification_update'),
    path('category/<int:category_id>/classification/<int:classification_id>/delete/',
         views.classification_delete, name='classification_delete'),

    # Data
    path('category/<int:category_id>/classification/<int:classification_id>/data/create_form/', views.data_create_form,
         name='data_create_form'),
    path('category/<int:category_id>/classification/<int:classification_id>/data/create/', views.data_create,
         name='data_create'),
    path('category/<int:category_id>/classification/<int:classification_id>/data/<int:data_id>/',
         views.data_detail, name='data_detail'),
    path('category/<int:category_id>/classification/<int:classification_id>/data/<int:data_id>/update_form/',
         views.data_update_form, name='data_update_form'),
    path('category/<int:category_id>/classification/<int:classification_id>/data/<int:data_id>/update/',
         views.data_update, name='data_update'),
    path('category/<int:category_id>/classification/<int:classification_id>/data/<int:data_id>/delete/',
         views.data_delete, name='data_delete'),

    # Search
    path('search/', views.search, name='search'),

    # payment
    path('payment/prohibition', views.payment_test, name='payment_prohibition'),
    path('payment/describe', views.payment_describe, name='payment_describe'),
    path('payment/', views.payment, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/fail/', views.payment_fail, name='payment_fail'),

    # Sitemap
    path('sitemap.xml', my_sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    # robots.txt
    path('robots.txt', serve, {'path': 'robots.txt',
         'document_root': settings.STATICFILES_DIRS[0]}),

    # Adsense
    re_path(r'^ads\.txt$', serve, {
        'path': 'ads.txt',
        'document_root': os.path.join(settings.STATICFILES_DIRS[0]),
    }),

    # Naver
    path('naver3a7b0c9f306d7cf81119e203ee3be4bf.html', serve, {
        'path': 'naver3a7b0c9f306d7cf81119e203ee3be4bf.html',
        'document_root': settings.STATICFILES_DIRS[0]
    }),
]

study_materials/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Subscription(models.Model):  # Subscription 모델 선언
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)  # User 모델과 1:1 관계 정의
    is_subscribed = models.BooleanField(default=False)  # 유료 구독 여부를 나타내는 필드
    start_date = models.DateTimeField(null=True, blank=True)  # 구독 시작일
    end_date = models.DateTimeField(null=True, blank=True)  # 구독 종료일
    payment_status = models.CharField(
        max_length=50, default='pending')  # 결제 상태
    billing_key = models.CharField(
        max_length=200, null=True, blank=True)  # 빌링키

    def __str__(self):
        return self.user.username + " subscription status: " + str(self.is_subscribed)

    @receiver(post_save, sender=User)  # User 모델 인스턴스가 저장되면 post_save 신호를 받음
    # User 모델이 저장된 후 실행될 함수
    def create_user_subscription(sender, instance, created, **kwargs):

        if created:  # User 인스턴스가 생성되었을 때만 실행
            Subscription.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_subscription(sender, instance, **kwargs):  # User 모델이 저장될 때마다 실행될 함수
        instance.subscription.save()


class Notice(models.Model):  # Notice 테이블
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    date = models.DateTimeField()


class Category(models.Model):  # Category 테이블
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    is_public = models.BooleanField(default=True)


class CategorySubscription(models.Model):  # 구독 정보를 담을 새로운 모델
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='category_subscriptions')
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='subscribers')

    class Meta:
        unique_together = ('user', 'category')  # 유저와 카테고리의 조합은 유일해야 함


class Classification(models.Model):  # Classification 테이블
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)


class Data(models.Model):  # Data 테이블
    classification = models.ForeignKey(
        Classification, on_delete=models.CASCADE)
    name = models.TextField()
    description = models.TextField()
    frequency = models.IntegerField()

    def save(self, *args, **kwargs):
        if self.frequency > 10:
            self.frequency = 10
        super(Data, self).save(*args, **kwargs)

my_study_materials/views.py
from django.shortcuts import render

my_study_materials/templates/categories.html
{% extends "layout.html" %}
{% load static %}

{% block content %}

    <style>
        /* 테이블 레이아웃 고정 */
        table {
            table-layout: fixed;
            width: 100%;  /* 테이블 전체 너비 설정 */
        }

        /* 행의 비율을 조정 */
        th:nth-child(1), td:nth-child(1) { width: 20%; }
        th:nth-child(2), td:nth-child(2) { width: 60%; }
        th:nth-child(3), td:nth-child(3) { width: 10%; }
        th:nth-child(4), td:nth-child(4) { width: 10%; }

        /* 텍스트가 셀을 벗어날 경우 ...으로 표시 */
        .ellipsis div {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 100%;
        }
    </style>

    <div class="container mt-4">
        <!-- 정렬 버튼 -->
        <div class="col-12 text-end"> 
            <a id="sortDataByName">
            <span class="sort-bold">이름순</span>
            <img id="sort-name-caret-icon" class="align-self-center" src="{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg'%}" alt="caret-up-fill" width="10" height="10" />  
            </a>
            |
            <a id="sortDataByFrequency">
            <span>인기순</span>
            <img id="sort-frequency-caret-icon" class="align-self-center" src="{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg'%}" alt="caret-up-fill" width="10" height="10" /> 
            </a>
        </div>

        <hr>

        <!-- 카테고리 목록 -->
        <div class="container">
            <table class="table table-striped-columns table-hover">
                <thead>
                    <tr>
                        <th class="text-center">제목</th>
                        <th class="text-center">설명</th>
                        <th class="text-center">아이디</th>
                        <th class="text-center">구독자 수</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                    <tr>
                        <td class="ellipsis text-center">
                            <div data-bs-toggle="tooltip" data-bs-placement="bottom">
                                <a class="text-decoration-none" href="{% url 'category_detail' category.id %}">{{ category.name }}</a>
                            </div>                            
                        </td>
                        <td class="ellipsis">
                            <div data-bs-toggle="tooltip" data-bs-placement="bottom">{{ category.description }}</div>
                        </td>
                        <td class="ellipsis text-center">
                            <div data-bs-toggle="tooltip" data-bs-placement="bottom">{{ category.user }}</div>
                        </td>
                        <td class="ellipsis text-center">
                            <div data-bs-toggle="tooltip" data-bs-placement="bottom">{{ category.subscriber_count }}</div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>
        // Tooltip
        document.addEventListener("DOMContentLoaded", function(){      
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl);
            });

            const ellipsisElements = document.querySelectorAll(".ellipsis div");

            ellipsisElements.forEach(function(element) {
                // 'span' 태그를 제외한 텍스트만 가져와 'title' 속성에 설정
                let textWithoutSpan = "";
                for (const node of element.childNodes) {
                    if (node.nodeType === 3) { // 텍스트 노드
                        textWithoutSpan += node.nodeValue;
                    }
                }
                element.setAttribute("title", textWithoutSpan.trim());
            });
        }); 
    </script>
{% endblock %}

my_study_materials/templates/category.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<div class="mt-5 gap-2 d-flex flex-column align-items-end">
  {% if category.user == user %}
    <p id="classification-settings" class="fw-bold" data-bs-toggle="collapse" data-bs-target="#classificationButtons">My Classification Settings
      <img id="classification-caret-icon" class="align-self-center ms-2" src="{% static 'bootstrap-icons-1.10.5/caret-down-fill.svg'%}" alt="caret-down-fill" width="10" height="10" />                   
    </p>
    <div class="collapse" id="classificationButtons">
      <ul class="list-unstyled">
        <li class="nav-item rounded gap-3">                
          <a type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#classificationCreateModal">추가</a>
          <a type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#classificationUpdateModal">수정</a>
          <a type="button" class="btn btn-sm btn-outline-danger" id="classificationDeleteBtn">삭제</a>
        </li>
      </ul>
    </div>
  {% else %}  
    {% if category_is_subscribed %}
      <span class="fs-3 fw-bold clickable" id="subscribeToggle">★</span>
    {% else %}
      <span class="fs-3 fw-bold clickable" id="subscribeToggle">☆</span>
    {% endif %}

    <span class="fs-3 fw-bold">구독자: {{ category.subscriber_count|default:"0" }}명</span>
  {% endif %}
</div>

<div class="container mt-5">
    <h2>
        <strong>
          <a class="text-decoration-none text-body" href="{% url 'category_detail' category_id=category.id %}">{{category.name}}</a>         
       </strong>
    </h2>
  <hr>
  <ul class="list-group" id="classificationList">
    {% for classification in classifications %}
      <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
        <a class="text-decoration-none" href="{% url 'classification_detail' category.id classification.id %}">{{ classification.name }}</a>
        <button type="button" class="btn btn-danger btn-sm delete-button" style="display: none;" id="deleteButton{{ classification.id }}">삭제</button>        
      </li>
    {% empty %}
      <li class="list-group-item text-muted">현재 목록이 존재하지 않습니다.</li>
    {% endfor %}
  </ul>
</div>

<!-- Modal -->
<!-- Create Classification-->
<div class="modal fade" id="classificationCreateModal" tabindex="-1" aria-labelledby="classificationCreateModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addClassificationModalLabel">목차 추가</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <input type="text" class="form-control" id="classification-name" name="name" placeholder="목차명">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
        <button type="button" class="btn btn-primary" id="saveClassificationBtn">추가하기</button>
      </div>
    </div>
  </div>
</div>

<!-- Update Classification -->
  <div class="modal fade" id="classificationUpdateModal" tabindex="-1" aria-labelledby="classificationUpdateModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">목차 수정</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="classification_update_form" method="post" action="{% url 'classification_update' category_id=category.id %}">
              {% csrf_token %}
               {% for classification in classifications %}
              <div class="mb-3">
                <!-- forloop.counter0: Django 템플릿 태그에서 사용되는 반복문의 카운터변수 -->
                <input type="hidden" name="classification_id_{{ forloop.counter0 }}" value="{{ classification.id }}">
                <input type="text" class="form-control" id="classificationName" name="classification_name_{{ forloop.counter0 }}" value="{{ classification.name }}" required>
              </div>
              {% endfor %}
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
            <button type="submit" class="btn btn-primary" form="classification_update_form">저장</button>
          </div>
        </div>
      </div>
    </div> 
  
<script>
  const isOwner = {% if category.user == user %}true{% else %}false{% endif %};

  // Category를 만든 사람인 경우
  if(isOwner) {
    // 목차 추가
    document.querySelector('#saveClassificationBtn').addEventListener('click', function() {
      const classificationName = document.querySelector('#classification-name').value;
      const data = new URLSearchParams();
      data.append('name', classificationName);
      fetch("{% url 'classification_create' category_id=category.id %}", {
        method: 'POST',
        body: data,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'X-CSRFToken': '{{ csrf_token }}'
        }
      }).then(function(response) {
        if (response.ok) {
          location.reload();
          return;
        } 
        return response.json().then(json => {
          if (json.message === "Maximum number of classifications reached") {
            alert("최대 목차 개수를 초과했습니다.");
          } else if (json.message === "Classification name already exists") {
            alert("이미 존재하는 목차 이름입니다.");
          } else {
            alert(json.message || "목차를 추가하는 도중 오류가 발생했습니다. 다시 시도해 주세요.");
          }
          throw new Error(`HTTP error! status: ${response.status}`);
        });      
      });
    });

    // 목차 수정
    document.querySelector('#classification_update_form').addEventListener('submit', function(e) {
      e.preventDefault();
      
      const formData = new FormData(document.querySelector('#classification_update_form'));

      fetch("{% url 'classification_update' category_id=category.id %}", {
        method: 'POST',
        body: formData,
        headers: {
          'X-CSRFToken': '{{ csrf_token }}'
        }
      })
      .then(response => {
        if (response.ok) {
          location.reload(); 
        } else {
          return response.json().then(json => { // 실패 시 오류 메시지 출력
            if (json.errors === "Classification name already exists") {
              alert("이미 존재하는 목차 이름입니다.");
            } else {
              alert(json.errors || "목차를 수정하는 도중 오류가 발생했습니다. 다시 시도해 주세요.");
            }
          });
        }
      })
      .catch(error => {
        console.error('Fetch Error:', error);
      });
    });

    // 목차 삭제
    document.getElementById('classificationDeleteBtn').addEventListener('click', function() {
      var classificationList = document.getElementById('classificationList').querySelectorAll('li');
      for (var i = 0; i < classificationList.length; i++) {
        var button = classificationList[i].querySelector('.delete-button');
        if (button) {
          var display = button.style.display;
          button.style.display = display === 'none' ? 'inline' : 'none';
        }
      }
    });

    // 각 삭제 버튼에 대한 이벤트 리스너 등록
    {% for classification in category.classification_set.all %}
    document.getElementById('deleteButton{{ classification.id }}').addEventListener('click', function() {
      deleteClassification({{ classification.id }});
    });
    {% endfor %}

    function deleteClassification(classificationId) {
      var categoryId = {{ category.id }};
      var url = '/category/' + categoryId + '/classification/' + classificationId + '/delete/'; // 삭제 URL

      fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'X-CSRFToken': '{{ csrf_token }}'
        },
      })
      .then(response => response.json())
      .then(data => {
        if (data.status === 'success') {
          document.getElementById('deleteButton' + classificationId).closest('.list-group-item').remove();
        } else {
          // 실패 시 에러 메시지 표시
          alert('삭제 실패: ' + data.error);
        }
      })
      .catch(error => {
        console.error('에러 발생:', error);
        alert('삭제 중 오류가 발생했습니다.');
      });
    }

    // classification 모양 변경
    document.addEventListener('DOMContentLoaded', function() {
      const classificationButtons = document.getElementById('classificationButtons'); 
      const classificationCaretIcon = document.getElementById('classification-caret-icon');

      classificationButtons.addEventListener('show.bs.collapse', function() {
        classificationCaretIcon.src = "{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg' %}";
      });

      classificationButtons.addEventListener('hide.bs.collapse', function() { 
        classificationCaretIcon.src = "{% static 'bootstrap-icons-1.10.5/caret-down-fill.svg' %}";
      });
    });

  } else {

    // 구독하기
    document.addEventListener("DOMContentLoaded", function() {
      const subscribeToggle = document.getElementById("subscribeToggle");
      const categoryId = {{ category.id }};
      
      subscribeToggle.addEventListener("mouseover", function() {
        this.style.cursor = "pointer";
      });
      
      subscribeToggle.addEventListener("mouseout", function() {
        this.style.cursor = "default";
      });
      
      subscribeToggle.addEventListener("click", function() {
        
        if (!{{ user.is_authenticated|yesno:"true,false" }}) {
          alert('로그인 후 이용이 가능합니다.');
          window.location.href = "{% url 'account_login' %}";
          return;
        }

        fetch(`/category/${categoryId}/subscribe/`, {
          method: 'POST',
          headers: {
            'X-Requested-With': 'XMLHttpRequest',  // AJAX 요청임을 명시
            'X-CSRFToken': getCookie('csrftoken')  // CSRF 토큰
          }
        })
        .then(response => response.json())
        .then(data => {
          if (data.status === 'subscribed') {
            subscribeToggle.textContent = "★";
          } else {
            subscribeToggle.textContent = "☆";
          }
          location.reload();

        });
      });
    });
  }

  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
</script>
{% endblock %}

my_study_materials/templates/classification.html
{% extends "layout.html" %}

{% block content %}
{% load static %}

<div class="d-flex justify-content-end mt-5 gap-2">
  {% if category.user == user %}
  <a href="{% url 'data_create_form' category_id=category_id classification_id=classification_id %}">
    <button type="button" class="btn btn-sm btn-outline-primary">데이터 추가</button>
  </a>
  {% endif %}
</div>

<div class="container py-4 px-4">
  <div class="row">
    <!-- 목차 -->
    <div class="col-12 text-start my-4"> 
      <h2>
        <strong>
          <a class="text-decoration-none text-body" href="{% url 'category_detail' category_id=category.id %}">{{category.name}}</a> &gt;
          <a class="text-decoration-none text-body" href="{% url 'classification_detail' category_id=category.id classification_id=classification.id %}">{{classification.name}}</a>
        </strong>
      </h2>
    </div>

    <!-- 정렬 버튼 -->
    <div class="col-12 text-end"> 
      <div>
        <a id="sortDataByName">
          <span class="sort-bold">이름순</span>
          <img id="sort-name-caret-icon" class="align-self-center" src="{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg'%}" alt="caret-up-fill" width="10" height="10" />  
        </a>
        |
        <a id="sortDataByFrequency">
          <span>빈도순</span>
          <img id="sort-frequency-caret-icon" class="align-self-center" src="{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg'%}" alt="caret-up-fill" width="10" height="10" /> 
        </a>
      </div>
    </div>
  </div>

  <hr>

  <ul class="list-group" id="classificationList">
  {% for data in first_page_data %}
    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      <a class="text-decoration-none" href="/category/{{category_id}}/classification/{{classification_id}}/data/{{data.id}}/">{{data.name}}</a>
    </li>
  {% endfor %}  
  </ul>
</div>
<script>
  // 데이터 정렬 및 페이지네이션(무한스크롤)
  let isFetching = false; // 현재 데이터를 불러오는 중인지 아닌지를 체크
  
  document.addEventListener('DOMContentLoaded', function() {
      fetchData(1, 'name', 'asc');

      let isNameAsc = true;
      let isFrequencyAsc = true;
      let currentPage = 1; // 현재 페이지
      let isLastPage = false;

      // fw-bold 클래스 추가/삭제 함수
      function toggleBold(elementId) {
        document.querySelectorAll('.sort-bold').forEach(elem => elem.classList.remove('sort-bold'));
        document.querySelector(`#${elementId}`).querySelector('span').classList.add('sort-bold');
      }

      // 데이터를 불러와서 화면을 갱신하는 함수
      function fetchData(page, sortBy, order) {
        isFetching = true;
        // Django 뷰에 요청
        fetch(`/category/{{category_id}}/classification/{{classification_id}}/?page=${page}&sortBy=${sortBy}&order=${order}`, {
          headers: {
              'X-Requested-With': 'XMLHttpRequest'
          }
         })          
        .then(response => response.json())
        .then(data => {
          let listHtml = '';
          data.data_list.forEach(item => {
           listHtml += `<li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"><a class="text-decoration-none" href="/category/{{category_id}}/classification/{{classification_id}}/data/${item.id}/">${item.name}</a></li>`;
          });
          document.getElementById('classificationList').innerHTML += listHtml;

          isLastPage = data.is_last_page;
          isFetching = false;
        });
      }

      const nameSortBtn = document.querySelector('#sortDataByName');
      const frequencySortBtn = document.querySelector('#sortDataByFrequency');

      let currentSort = 'name';  // 현재 정렬 기준을 저장하는 변수
      let currentOrder = 'asc';  // 현재 정렬 순서를 저장하는 변수

      // 스크롤 이벤트 등록
      window.addEventListener("scroll", function() {
        if (!isLastPage && !isFetching && window.innerHeight + window.scrollY >= document.body.offsetHeight) {
          // 페이지 하단에 도달했을 때
          isFetching = true;
          currentPage++;
          fetchData(currentPage, currentSort, currentOrder);
        }
      });

      // 각 정렬 버튼에 이벤트 리스너 부착
      nameSortBtn.addEventListener('click', function() {
        toggleBold('sortDataByName');
        document.getElementById('classificationList').innerHTML = ''; // 리스트 초기화
        isNameAsc = !isNameAsc; // 상태 토글
        currentSort = 'name';
        currentOrder = isNameAsc ? 'asc' : 'desc';
        currentPage = 1;
        fetchData(currentPage, currentSort, currentOrder);
        
        // 이미지 변경
        let nameCaretIcon = document.querySelector('#sort-name-caret-icon');
        nameCaretIcon.src = isNameAsc ? "{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg' %}" : "{% static 'bootstrap-icons-1.10.5/caret-down-fill.svg' %}";
      });

      frequencySortBtn.addEventListener('click', function() {
        toggleBold('sortDataByFrequency');
        document.getElementById('classificationList').innerHTML = ''; // 리스트 초기화
        isFrequencyAsc = !isFrequencyAsc; // 상태 토글
        currentSort = 'frequency';
        currentOrder = isFrequencyAsc  ? 'asc' : 'desc';
        currentPage = 1;
        fetchData(currentPage, currentSort, currentOrder);        

        // 이미지 변경
        let frequencyCaretIcon = document.querySelector('#sort-frequency-caret-icon');
        frequencyCaretIcon.src = isFrequencyAsc ? "{% static 'bootstrap-icons-1.10.5/caret-up-fill.svg' %}" : "{% static 'bootstrap-icons-1.10.5/caret-down-fill.svg' %}";
      });
  }); 
</script>
{% endblock %}

my_study_materials/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

<div class="d-flex justify-content-end mt-5 gap-2">
  {% if user.is_superuser %}
  <a href="{% url 'notice_create_form' %}">
    <button type="button" class="btn btn-outline-primary">글쓰기</button>
  </a>
  {% endif %}
</div>

<div class="container">
  <div class="row justify-content-center align-items-center" style="height: 50vh;">
    <div class="col-md-8">
      <h3 class="text-center mb-4">공지사항</h3>
      <table class="table table-striped table-hover">
        <colgroup>
          <col style="width: 70%;">
          <col style="width: 30%;">
        </colgroup>
        <thead>
          <tr class="text-center">
            <th scope="col">제목</th>
            <th scope="col">날짜</th>
          </tr>
        </thead>
        <tbody>
          {% for notice in notices %}
          <tr class="text-center">
            <td><a class="text-decoration-none" href="{% url 'notice_detail' notice.id %}">{{ notice.title }}</a></td>
            <td>{{ notice.date|date:"Y-m-d" }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}